export interface FormData {
    city: string;
    townSector: string;
    location: string;
    landmark: string;
    Bhk: string;
    maxprice: string;
    minprice: string;
    ageOfProperty: string;
    totalFloor : number;
    waterSupply: string;
    powerBackup: string;
    noticePeriod: string;
    totalPG: number;
    bedCount: number;
    foodAvailable: boolean | string;
    timeRestriction: boolean | string;
    security: string; 
    maintenance: string;
    totalRoom : number;
    bedcount : number;
    noofGuests: number;
    totalFlat: number;
    offer: string;
    listingShowNo: string;
    careTaker: string;
    luxury: string;
    address: string;
    adress: string;
    furnishingType: string;
    accomoType: string;
    petsAllowed: string;
    genderPrefer: string;
    flatType: string;
    parking: string[];
    preferTenants: string[];
    insideFacilities: string[];
    outsideFacilities: string[];
  }
